### ISSUE TITLE
SSL_ERROR_BAD_CERT_DOMAIN

### ISSUE THREAD

**Issue by trikadin** [formatjs/formatjs.github.io#4] opened 2024-10-17 13:37 UTC
failed to access the site using chrome and firefox

<img width="530" alt="image" src="https://github.com/user-attachments/assets/dbdde3b3-c9f5-40a3-a1ef-aae6ef27bc50">
<img width="809" alt="image" src="https://github.com/user-attachments/assets/2c252567-e5a1-48d4-95b2-455e93c45d5f">

```
https://formatjs.io/docs/core-concepts/icu-syntax/#date-type

Unable to communicate securely with peer: requested domain name does not match the server’s certificate.

HTTP Strict Transport Security: false
HTTP Public Key Pinning: false

Certificate chain:

-----BEGIN CERTIFICATE-----
MIIKezCCCWOgAwIBAgIQB/797rJj/U8TBEtvJT+4ZDANBgkqhkiG9w0BAQsFADBw
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMS8wLQYDVQQDEyZEaWdpQ2VydCBTSEEyIEhpZ2ggQXNz
dXJhbmNlIFNlcnZlciBDQTAeFw0yNDA3MzAwMDAwMDBaFw0yNTAxMjIyMzU5NTla
MGoxCzAJBgNVBAYTAlVTMREwDwYDVQQIEwhOZXcgWW9yazERMA8GA1UEBxMITmV3
IFlvcmsxHDAaBgNVBAoTE1lhaG9vIEhvbGRpbmdzIEluYy4xFzAVBgNVBAMTDnNy
YzEueWFob28uY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE4Gz2W0I1/x5e
MndsyZmJWdmfTLIemAD6arWmL7fEWRJb7KhSArNUsvCkXtOutKNWiJhZTiCbC308
TytaWfMNJaOCB+AwggfcMB8GA1UdIwQYMBaAFFFo/5CvAgd1PMzZZWRiohK4WXI7
MB0GA1UdDgQWBBTrSraOrDOW8lTcpXnDkbTfl/KqKTCCBJ0GA1UdEQSCBJQwggSQ
gg5zcmMxLnlhaG9vLmNvbYIKKi5vYXRoLmNvbYINKi5vdXJvYXRoLmNvbYIOKi5v
dXJ5YWhvby5jb22CCyoueWFob28uY29tggkqLmFvbC5jb22CCCouYW9sLmRlghIq
LnZlcml6b25tZWRpYS5jb22CDioueWFob29pbmMuY29tggoqLnlhaG9vLmJnggoq
LnlhaG9vLmNhggoqLnlhaG9vLmNugg0qLnlhaG9vLmNvLmlugg0qLnlhaG9vLmNv
Lm56gg0qLnlhaG9vLmNvLnRogg0qLnlhaG9vLmNvLnVrgg4qLnlhaG9vLmNvbS5h
coIOKi55YWhvby5jb20uYXWCDioueWFob28uY29tLmJygg4qLnlhaG9vLmNvbS5j
boIOKi55YWhvby5jb20uaGuCDioueWFob28uY29tLm14gg4qLnlhaG9vLmNvbS5w
aIIOKi55YWhvby5jb20uc2eCDioueWFob28uY29tLnR3gg4qLnlhaG9vLmNvbS52
boIOKi55YWhvby5jb20ubXmCDSoueWFob28uY28uaWSCCioueWFob28uZGWCCiou
eWFob28uZWWCCioueWFob28uZXOCCioueWFob28uZnKCCioueWFob28uaGuCCiou
eWFob28uaHWCCioueWFob28uaWWCCioueWFob28uaW6CCioueWFob28uaXSCCiou
eWFob28ucGiCCioueWFob28ucHSCCioueWFob28uc2eCECouYnJpZ2h0cm9sbC5j
b22CDSoub3BzLmFvbC5jb22CDSoud2ViLmFvbC5jb22CCyouYW9sLmNvLnVrgggq
LmFvbC5qcIIOKi5lbmdhZGdldC5jb22CDSoudGVhbWFvbC5jb22CCCouYW9sLmZy
gggqLmFvbC5jYYINKi5qb3lzdGlxLmNvbYINKi5tYWt0b29iLmNvbYIPKi55YWhv
b2FwaXMuY29tghAqLnlhaG9vbXVzaWMuY29tghAqLnZ6YnVpbGRlcnMuY29tghMq
Lm9uZW1vYmlsZS5hb2wuY29tggwqLm1ha2Vycy5jb22CEiouaXNwLm5ldHNjYXBl
LmNvbYIVKi55YWhvb3Nwb3J0c2Jvb2suY29tgg8qLmlzcC55YWhvby5jb22CEyou
Z2xwLnNlYXJjaGphbS5jb22CGCoubm90ZG9uZWRvY3VtZW50YXJ5LmNvbYIRKi5u
b3Rkb25lZmlsbS5jb22CESoueWFob29zcG9ydHMuY29tghIqLnlhaG9vZmluYW5j
ZS5jb22CFyouYnJvbWFuLnZ6YnVpbGRlcnMuY29tghUqLmtub3dsZWRnZS55YWhv
by5jb22CFyouYWR2ZXJ0aXNpbmcueWFob28uY29tghIqLmJ1aWx0YnlnaXJscy5j
b22CCyoueWFob28ubmV0ghgqLnlhaG9vc21hbGxidXNpbmVzcy5jb22CCyouZ2Ft
ZXMuY29tghIqLnRlY2hjcnVuY2hpdC5jb22CECouY3J1bmNoZ2Vhci5jb22CEiou
bW9iaWxlY3J1bmNoLmNvbTA+BgNVHSAENzA1MDMGBmeBDAECAjApMCcGCCsGAQUF
BwIBFhtodHRwOi8vd3d3LmRpZ2ljZXJ0LmNvbS9DUFMwDgYDVR0PAQH/BAQDAgOI
MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjB1BgNVHR8EbjBsMDSgMqAw
hi5odHRwOi8vY3JsMy5kaWdpY2VydC5jb20vc2hhMi1oYS1zZXJ2ZXItZzYuY3Js
MDSgMqAwhi5odHRwOi8vY3JsNC5kaWdpY2VydC5jb20vc2hhMi1oYS1zZXJ2ZXIt
ZzYuY3JsMIGDBggrBgEFBQcBAQR3MHUwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3Nw
LmRpZ2ljZXJ0LmNvbTBNBggrBgEFBQcwAoZBaHR0cDovL2NhY2VydHMuZGlnaWNl
cnQuY29tL0RpZ2lDZXJ0U0hBMkhpZ2hBc3N1cmFuY2VTZXJ2ZXJDQS5jcnQwDAYD
VR0TAQH/BAIwADCCAX0GCisGAQQB1nkCBAIEggFtBIIBaQFnAHYATnWjJ1yaEMM4
W2zU3z9S6x3w4I4bjWnAsfpksWKaOd8AAAGRAieQbgAABAMARzBFAiEA2EB6cpnV
xDKbP4D8IuxurNenv1gE3TIH7LivboVrk44CIBCnywjYVGWGCxlp3BLAYkVO1i4C
p+rYYNiZ0+KNWwm+AHYAfVkeEuF4KnscYWd8Xv340IdcFKBOlZ65Ay/ZDowuebgA
AAGRAieQVgAABAMARzBFAiBg4Hi8YxcoqrryJ+K2XNDvD48G6oD4aM0QoipSsKPH
vAIhAIWpaTHPrbdtu8VehYv9Rk81eZrbuSq+8+utmfDazmeDAHUA5tIxY0B3jMEQ
QQbXcbnOwdJA9paEhvu6hzId/R43jlAAAAGRAieQQwAABAMARjBEAiAfo7DKza0d
oljvM+jstpfMqtDnMqw3gjWhQoS29rJxKAIgXvDqQV1fa45bzGXVdi9ym92fJ6Y1
ICaIqaCc5QMTID4wDQYJKoZIhvcNAQELBQADggEBAJ2f+HiwFB6oRPcixeuLGFXF
qmNzBYb17yJ+R3eoHBsovsluSGn2OENfqQAEgjmNbaVi+GOjNZlIqlHLPRtTpZPU
20qtJPTRTnC/otg828hxmnWr0/+NsiwBzzkSm3KiLUnmG1vpsq9VGsPCPt+6KPOn
1435PEzrBHpYXAlFqVe+f77aUXrCUDwfIEEajq6KIGcvnlEJJ9BCp40pOSzWYswx
EAe1ie/RMxk1oDQAi/Ix4zBFwjlPab8M416HBaMEwqF8J/uK4hkV/BhGuPOinJQF
rVWXUt4BSuNQkQdAKgjlfj4uNGobq/CXOpJjBEVIYI88MY1COD27KcLzTyfpPTs=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIEsTCCA5mgAwIBAgIQBOHnpNxc8vNtwCtCuF0VnzANBgkqhkiG9w0BAQsFADBs
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSswKQYDVQQDEyJEaWdpQ2VydCBIaWdoIEFzc3VyYW5j
ZSBFViBSb290IENBMB4XDTEzMTAyMjEyMDAwMFoXDTI4MTAyMjEyMDAwMFowcDEL
MAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3
LmRpZ2ljZXJ0LmNvbTEvMC0GA1UEAxMmRGlnaUNlcnQgU0hBMiBIaWdoIEFzc3Vy
YW5jZSBTZXJ2ZXIgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC2
4C/CJAbIbQRf1+8KZAayfSImZRauQkCbztyfn3YHPsMwVYcZuU+UDlqUH1VWtMIC
Kq/QmO4LQNfE0DtyyBSe75CxEamu0si4QzrZCwvV1ZX1QK/IHe1NnF9Xt4ZQaJn1
itrSxwUfqJfJ3KSxgoQtxq2lnMcZgqaFD15EWCo3j/018QsIJzJa9buLnqS9UdAn
4t07QjOjBSjEuyjMmqwrIw14xnvmXnG3Sj4I+4G3FhahnSMSTeXXkgisdaScus0X
sh5ENWV/UyU50RwKmmMbGZJ0aAo3wsJSSMs5WqK24V3B3aAguCGikyZvFEohQcft
bZvySC/zA/WiaJJTL17jAgMBAAGjggFJMIIBRTASBgNVHRMBAf8ECDAGAQH/AgEA
MA4GA1UdDwEB/wQEAwIBhjAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
NAYIKwYBBQUHAQEEKDAmMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2Vy
dC5jb20wSwYDVR0fBEQwQjBAoD6gPIY6aHR0cDovL2NybDQuZGlnaWNlcnQuY29t
L0RpZ2lDZXJ0SGlnaEFzc3VyYW5jZUVWUm9vdENBLmNybDA9BgNVHSAENjA0MDIG
BFUdIAAwKjAoBggrBgEFBQcCARYcaHR0cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQ
UzAdBgNVHQ4EFgQUUWj/kK8CB3U8zNllZGKiErhZcjswHwYDVR0jBBgwFoAUsT7D
aQP4v0cB1JgmGggC72NkK8MwDQYJKoZIhvcNAQELBQADggEBABiKlYkD5m3fXPwd
aOpKj4PWUS+Na0QWnqxj9dJubISZi6qBcYRb7TROsLd5kinMLYBq8I4g4Xmk/gNH
E+r1hspZcX30BJZr01lYPf7TMSVcGDiEo+afgv2MW5gxTs14nhr9hctJqvIni5ly
/D6q1UEL2tU2ob8cbkdJf17ZSHwD2f2LSaCYJkJA69aSEaRkCldUxPUd1gJea6zu
xICaEnL6VpPX/78whQYwvwt/Tv9XBZ0k7YXDK/umdaisLRbvfXknsuvCnQsH6qqF
0wGjIChBWUMo0oHjqvbsezt3tkBigAVBRQHvFwY+3sAzm2fTYS5yh+Rp/BIAV0Ae
cPUeybQ=
-----END CERTIFICATE-----
```

**Comment by longlho** [comment] 2024-10-17 14:18
we're in the process of transitioning formatjs.io to a redirect so for future reference you can visit formatjs.github.io directly

**Comment by longlho** [comment] 2024-10-18 13:13
dupe of https://github.com/formatjs/formatjs/issues/4588

**Closed as completed by longlho** 2024-10-18 13:13 UTC
